INSERT INTO tb_category(name, created_At) VALUES ('Books', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Computers', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smartphones', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tablets', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Home Appliances', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fashion', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Shoes', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Watches', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Furniture', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Toys', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Beauty & Personal Care', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Health & Wellness', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Groceries', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Office Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Sports & Outdoors', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Automotive', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Pet Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Musical Instruments', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Baby Products', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Gardening', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Tools & Home Improvement', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Kitchen & Dining', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Movies & TV Shows', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Video Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Board Games', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Art & Crafts', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Photography', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Software', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Travel Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Outdoor Gear', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cycling', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Fitness Equipment', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Jewelry', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Handbags & Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Eyewear', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Smart Home Devices', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Drones & Accessories', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Car Electronics', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Stationery', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Bedding & Bath', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Luggage & Travel Gear', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Cleaning Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Lighting & Lamps', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Party Supplies', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Industrial & Scientific', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Collectibles', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Vintage Items', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Luxury Goods', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Specialty Foods', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Craft Beer & Spirits', NOW());
INSERT INTO tb_category(name, created_At) VALUES ('Subscription Services', NOW());
